---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: ansible-lint
platforms:
  - name: instance-1
    box: boxcutter/ubuntu1604
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
  options:
    spec: yes
