---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: boxcutter/ubuntu1604

suites:
  - name: default
    run_list:
      - recipe[myapp_chef::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
